### ISSUE TITLE
Queue 操作有问题

### ISSUE THREAD

**Issue by ushuz** [xiachufang/pylogrotate#2]
- 最早的 queue 文件会在某种情景下被删除，后续再操作该文件时由于文件不存在报错
- 长时间阻塞后队列会满，无法续传

**Comment by cadl** [comment]
之前还碰到一次 https://github.com/xiachufang/pylogrotate/blob/master/pylogrotate/main.py#L236 `self.queue.get_nowait()` 返回 None 的情况，然后直接跳入 258L 无限循环了。

**Comment by ushuz** [comment]
好像是由于并发引起的，在配合 flock 使用后这个问题不太明显了
