### ISSUE TITLE
按时间汇总有问题

### ISSUE THREAD

**Issue by ushuz** [xiachufang/pylogrotate#4]
每小时文件夹中保存的日志有 5 分钟偏移量，比如 `15/` 中保存的实际上是 14:55 - 15:55 的日志。算法那边反馈这个对他们有影响。

cc @xiachufang/algorithm

**Comment by morefreeze** [comment]
我以前看过一种类似实现是 向后晚5分钟，即实际时间16:05生成15:00-15:59的数据，命名还是15点
我觉得这个是可以接受的

**Comment by ushuz** [comment]
@morefreeze 生成时间是不保证的，比如网络卡了或者别的，生成时间可能差很大，只要命名对的上就可以

**Comment by morefreeze** [comment]
xx05可以认为是最早生成时间
主要还是命名和内容对上

**Comment by morefreeze** [comment]
我搞清楚了，logrotate生成一直是这样，需要用logreader 来读日志，它会解析nginx日志并根据时间来决定是否yield一行日志
@xiachufang/algorithm 
可以close了
